#!/usr/bin/env bash
# Download third-party SVG cards into docs/generated/.
# Stats and top-langs are generated by github-readme-stats-action in CI;
# this script fetches the remaining cards (streak, activity graph, trophies).
# Uses retry with exponential backoff; individual failures are non-fatal
# so previously committed SVGs remain usable.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/generated"
mkdir -p "$OUT"
USER="${GH_USERNAME:-talorlik}"

FAILURES=0

curl_retry() {
  local url=$1
  local output=$2
  local label=$3
  local max_attempts=4
  local attempt=1
  local delay=3

  while [ $attempt -le $max_attempts ]; do
    if curl -fsSL --max-time 15 "$url" -o "$output" 2>/dev/null; then
      echo "  [OK]  $label" >&2
      return 0
    fi
    if [ $attempt -lt $max_attempts ]; then
      echo "  [RETRY] $label (attempt $attempt/$max_attempts, next in ${delay}s)" >&2
      sleep $delay
      delay=$((delay * 2))
    fi
    ((attempt++))
  done

  echo "  [FAIL] $label (all $max_attempts attempts exhausted, keeping existing file)" >&2
  FAILURES=$((FAILURES + 1))
  return 1
}

# Try multiple mirrors for a single asset; first success wins.
curl_mirror() {
  local output=$1
  local label=$2
  shift 2

  for url in "$@"; do
    if curl -fsSL --max-time 15 "$url" -o "$output" 2>/dev/null; then
      echo "  [OK]  $label" >&2
      return 0
    fi
  done

  echo "  [FAIL] $label (all mirrors exhausted, keeping existing file)" >&2
  FAILURES=$((FAILURES + 1))
  return 1
}

TOTAL=0

echo "Fetching SVG assets..." >&2

TOTAL=$((TOTAL + 1))
curl_retry \
  "https://streak-stats.demolab.com?user=${USER}&theme=tokyonight&hide_border=true&date_format=M%20j%5B%2C%20Y%5D" \
  "$OUT/streak.svg" \
  "streak.svg"

TOTAL=$((TOTAL + 1))
curl_retry \
  "https://github-readme-activity-graph.vercel.app/graph?username=${USER}&theme=tokyo-night&hide_border=true&area=true" \
  "$OUT/github-activity.svg" \
  "github-activity.svg"

TROPHY_PARAMS="?username=${USER}&theme=tokyonight&no-frame=true&no-bg=true&margin-w=10&row=1"
TOTAL=$((TOTAL + 1))
curl_mirror \
  "$OUT/trophies.svg" \
  "trophies.svg" \
  "https://github-profile-trophy-kannan.vercel.app/${TROPHY_PARAMS}" \
  "https://trophy.ryglcloud.net/${TROPHY_PARAMS}" \
  "https://github-profile-trophy-tawny.vercel.app/${TROPHY_PARAMS}" \
  "https://gh-trophy.cdnsoft.net/${TROPHY_PARAMS}" \
  "https://trophygh.kolioaris.xyz/${TROPHY_PARAMS}" \
  "https://github-profile-trophy-orcin-eta.vercel.app/${TROPHY_PARAMS}"

if [ $FAILURES -gt 0 ]; then
  echo "SVG fetch: $FAILURES of $TOTAL downloads failed (stale files retained)." >&2
fi

exit 0
